version: "3"

services:
  httpd-server:
    container_name: httpd-server
    image: z7zmey/nginx-push-stream
    restart: always
    networks:
      default:
        aliases:
          - django
    ports:
      - "80:80"
    volumes:
      - ./:/usr/local/julython.org
      - ./conf/nginx/:/etc/nginx

  django:
    command: [newrelic-admin, run-program, python, /usr/local/julython.org/manage.py, runserver, "0.0.0.0:8036"]
    container_name: django
    image: julython-python
    restart: always
    environment:
      ENV: julython
    networks:
      default:
        aliases:
          - django
    ports:
      - "8036:8036"
    volumes:
      - ./:/usr/local/julython.org
